### ISSUE TITLE
Upgrading from 1.15.0 to 1.15.1 breaks jquery-validation-unobtrusive when using Browserify setup

### ISSUE THREAD

**Issue by ryanelian** [jzaefferer/jquery-validation#1829]
### Subject of the issue
I am using a Browserify-based setup for developing ASP.NET MVC application using jquery-validation and jquery-validation-unobtrusive:

![aspnet-entry](https://cloud.githubusercontent.com/assets/8892187/17144921/a90e0486-5382-11e6-9223-2d2b94b240b0.PNG)

![aspnet-validate](https://cloud.githubusercontent.com/assets/8892187/17144120/eac953ec-537f-11e6-94ca-14e32b31f974.PNG)

This works fine using jquery-validation up to version 1.15.0 but suddenly breaks when I upgrade the package to 1.15.1.

### Your environment
Version: 1.15.1
Browser: Firefox 48.0b10 and Chrome 52.0.2743.82 m

### Steps to reproduce
In an ASP.NET MVC Core web application, use Browserify setup like above, refer from the MVC View page, then test using a View Model and Form like these:

```csharp
public class TestModel
{
    [Required]
    public string Name { set; get; }
}
```

```html
@model Models.TestModel

<form method="post">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
</form>
```

### Expected behaviour
jquery-validation-unobtrusive works.

### Actual behaviour
This error appears in browser console `Uncaught TypeError: Cannot set property 'unobtrusive' of undefined` 
in jquery-validation-unobtrusive source: `$jQval.unobtrusive = {` 
where `var $jQval = $.validator`

So apparently `$.validator` becomes not defined due to upgrading from 1.15.0 to 1.15.1! 

When I actually commented out the part about requiring `jquery-validation-unobtrusive`, something like:

```javascript
global.derp = require('jquery');
require('jquery-validation');
//require('jquery-validation-unobtrusive/jquery.validate.unobtrusive');
```

Version 1.15.0, `derp.validator` invoked in console gives me `function [7]</</e.validator()`,
while version 1.15.1, `derp.validator` invoked in console gives me `undefined` instead!

**Comment by Arkni** [comment]
Just tested and everything works as expected. I roughly used the same code you provided:

### Structure
```
.
├── bundle.js
├── index.html
├── main.js
├── script.js
└── node_modules
    └── jquery-validation@1.15.1
        └── jquery@2.2.4
```

### `script.js`
```js
"use strict";

// you can also use `$`
global.jQuery = require("jquery");
require("jquery-validation");
```

### `main.js`
```js
"use strict";

require("./script");
```

### `index.html`
```html
<!DOCTYPE html>
<html>
<head>
    <title>jQuery-validation@1.15.1 with browserify</title>
</head>
<body>
    <form id="myform">
        <input type="text" name="name" required=""></input>
        <input type="submit" value="submit"></input>
    </form>
    <script type="text/javascript" src="./bundle.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            jQuery("#myform").validate();
        });
    </script>
</body>
</html>
```

**Comment by staabm** [comment]
In 1.15.1 we didnt change anything build or AMD related.. its unlikely we broke things with 1.15.1.. maybe with 1.15.0 but not with the latest release.

**Comment by FutureGUIs** [comment]
I have a similar issue using webpack.  I'm still getting used to webpack, but I found that a change in 1.15.1 in the additional-methods.js file on line 718 from` jQuery.validator.addMethod( "notEqualTo", function( value, element, param ) {` to this `$.validator.addMethod( "notEqualTo", function( value, element, param ) {` is what's breaking it for me, notice the $ from jQuery change.

**Comment by ryanbrandenburg** [comment]
I'm one of the maintainers on [jquery-validation-unobtrusive](https://github.com/aspnet/jquery-validation-unobtrusive). While trying to add UMD support we've run into basically the same issue, though in my debugging it doesn't appear to be dependent on 1.15.1 vs 1.15.0.

As @Arkni has said, you can prevent `Uncaught TypeError: Cannot set property 'unobtrusive' of undefined` under the CommonJS/Browserify/Node pattern if you have
```
global.jQuery = require("jquery");
require("jquery-validation");
```
But that has the problem that we've defeated the point (as I understand it) of using modules by polluting the global namespace. In diagnosing and toying around with this issue I found that if we `return $;` inside `jquery.validate.js` then use the result of that inside `jquery.validation.unobtrusive` it works without having to pollute the global. 

Is there some reason why making it return the extended jquery wouldn't work or would be wrong/bad? Or are we missing some existing way to use jquery-validation in the CommonJS pattern without polluting the namespace (or maybe I misunderstand, and that wouldn't actually be bad)?

**Comment by Arkni** [comment]
> In diagnosing and toying around with this issue I found that if we return $;

+1 to this. We can follow [this interesting approach](https://github.com/umdjs/umd/blob/95563fd6b46f06bda0af143ff67292e7f6ede6b7/templates/jqueryPlugin.js#L8-L24) (background umdjs/umd#68) which should fix the problem:
```js
module.exports = function( root, jQuery ) {
    if ( jQuery === undefined ) {
        // require("jQuery") returns a factory that requires window to
        // build a jQuery instance, we normalize how we use modules
        // that require this pattern but the window provided is a noop
        // if it's defined (how jquery works)
        if ( typeof window !== "undefined" ) {
            jQuery = require("jquery");
        } else {
            jQuery = require("jquery")(root);
        }
    }

    factory(jQuery);

    return jQuery;
};
```

**Comment by itsrachelfish** [comment]
I'm using webpack and jquery-validation works in 1.15.0 and is broken in 1.15.1. error message is:

```
TypeError: $(...).validate is not a function
```

When inspecting the generated file, it looks like webpack is trying to replace the Require.js definition instead of the CommonJS require statement.

```
	(function( factory ) {
		if ( true ) {
			!(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__(1)], __WEBPACK_AMD_DEFINE_FACTORY__ = (factory), __WEBPACK_AMD_DEFINE_RESULT__ = (typeof __WEBPACK_AMD_DEFINE_FACTORY__ === 'function' ? (__WEBPACK_AMD_DEFINE_FACTORY__.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__)) : __WEBPACK_AMD_DEFINE_FACTORY__), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
		} else if (typeof module === "object" && module.exports) {
			module.exports = factory( require( "jquery" ) );
		} else {
			factory( jQuery );
		}
	}(function( $ ) {
```

Reverting to 1.15.0 in my project for now. :+1:

**Comment by staabm** [comment]
Does @Arkni's patch posted above work for you?

**Comment by itsrachelfish** [comment]
@staabm I fixed it locally (before reverting to version 1.15.0) by switching the order of the if statements. If the CommonJS check for module.exports is put first, then it works fine

**Comment by ryanbrandenburg** [comment]
I've made #1838 with my proposed fix for this issue.

**Comment by mnpenner** [comment]
I just hit this error when upgrading from 1.15.0 to 0.17.0, so this still appears to be a problem. What's the solution?

I'm using webpack 3 with AMD disabled. I'm trying with

```js
const $ = global.$ = global.jQuery = require('jquery');
require('jquery-validation');
```

**Comment by rediris** [comment]
@mnpenner 

Managed to resolve a similar issue I was hacking by using `v1.17.0` and changing my `webpack.config.js` file:

```
import webpack from 'webpack';

module.exports = {
  module: {
    rules: [
      {
        test: /.js$/,
        use: [
          {
            loader: 'babel-loader',
          }
        ]
      }
    ]
  },
  plugins: [
    new webpack.ProvidePlugin({
      'window.jQuery': 'jquery',
      'window.$': 'jquery',
      'jQuery': 'jquery',
      '$': 'jquery',
    }),
  ],
  resolve: {
    alias: {
      jquery: 'jquery/src/jquery',
      validate: 'jquery-validation/dist/jquery.validate.js'
    },
    modules: [
      path.resolve('./src/**/js/'),// path to my JS source files
      path.resolve('./node_modules/')// path to my node modules folder
    ]
  }
}
```
And in my main JS file:
```
import 'validate';
```

Works for me now.

**Comment by vijaybritto** [comment]
Faced this issue in 1.15.1. Upgraded to 1.17.0. Resolved. This is all the code.
```javascript
window.$ = window.jQuery = require("jquery");
require('jquery-validation');
```

**Comment by henrypenny** [comment]
This resolved the issue for me:

`import 'imports-loader?jQuery=jquery,define=>false,module.exports=>false!jquery-validation'`
